### PR TITLE
NUCJODATIME-23: Fixed inconsistent value conversion when using differ…

### PR DESCRIPTION
**Pull request by RodrigoQuesadaDev**
…ent timezones for LocalDate fields persisted as SqlDate datastore type.

### CODE REVIEW

**Comment by andyjefferson** [comment]
Thanks for the contribution, now in GitHub master.
Note that the test is not in GitHub since it would have imposed a Java8 requirement on the datanucleus-jodatime plugin, and that is not allowed. If you want a test for this, please add it to the "tests" plugin under jdo/general, which does allow java 8, and already imports assertj-core

**Comment by RodrigoQuesadaDev** [comment]
Whoa you guys rock, thanks for your prompt response Andy. The version of AssertJ I added was 2.20 (Java 7 and up http://joel-costigliola.github.io/assertj/assertj-core.html) but the tests I added should also work with 1.X. :)

Do I still need to add them to that tests plugin under jdo/general?

**Comment by andyjefferson** [comment]
I put them in "tests".

**Comment by RodrigoQuesadaDev** [comment]
Awesome, thank you!

**Pull request merged**
